#docker-compose run test-vm
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  test-vm:
    image: shershulia/ctf-test:latest
    ports:
      - "22:22"
    stdin_open: true
    tty: true
    command: /bin/bash -c "sudo apt update && cd /ctf-ics && /bin/bash"
volumes:
  pgdata: {}
