#docker-compose run test-vm
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ics-ctf-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  test-vm:
    image: shershulia/ctf-test:latest
    ports:
      - "22:22"
      - "8080:8080"
    stdin_open: true
    tty: true
    command: /bin/bash -c "sudo apt update && cd /ctf-ics && /bin/bash"
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
volumes:
  pgdata: {}
